#!/usr/bin/env node
/**
 * One-shot installer: npm deps, DSH links, env file, dump-config check.
 * Run from the package: `node scripts/setup.mjs --bind YOUR_PUBLIC_IP`
 */
import { spawnSync } from 'node:child_process'
import { mkdirSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const win = process.platform === 'win32'

function help() {
  process.stdout.write(`Usage: node scripts/setup.mjs [options]

  --bind <ipv4>       public unicast IPv4 to listen/advertise (never 0.0.0.0)
  --advertise <ipv4>  override advertise address (defaults to --bind)
  --port <n>          projection port (default 50051)
  --web-port <n>      loopback dsh web port (default 3180)
  --skip-npm          skip npm install --omit=dev
`)
}

function parse(argv) {
  const out = { bind: '', advertise: '', port: '', webPort: '', skipNpm: false }
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i]
    const next = () => {
      const v = argv[i + 1]
      if (!v || v.startsWith('-')) {
        process.stderr.write(`setup: ${a} needs a value\n`)
        process.exit(2)
      }
      i += 1
      return v
    }
    if (a === '--bind') out.bind = next()
    else if (a === '--advertise') out.advertise = next()
    else if (a === '--port') out.port = next()
    else if (a === '--web-port') out.webPort = next()
    else if (a === '--skip-npm') out.skipNpm = true
    else if (a === '-h' || a === '--help') {
      help()
      process.exit(0)
    } else {
      process.stderr.write(`setup: unknown argument ${a}\n`)
      help()
      process.exit(2)
    }
  }
  if (out.bind === '0.0.0.0') {
    process.stderr.write('setup: refusing 0.0.0.0; pass a unicast IPv4.\n')
    process.exit(2)
  }
  if (out.bind && !out.advertise) out.advertise = out.bind
  return out
}

function shellQuote(value) {
  if (/^[A-Za-z0-9_./:@+-]+$/.test(value)) return value
  return `'${String(value).replace(/'/g, `'\\''`)}'`
}

function run(command, args, opts = {}) {
  const result = spawnSync(command, args, {
    cwd: root,
    stdio: 'inherit',
    shell: win,
    ...opts,
  })
  if ((result.status ?? 1) !== 0) process.exit(result.status ?? 1)
}

function hasCommand(name) {
  const probe = win
    ? spawnSync('where.exe', [name], { encoding: 'utf8' })
    : spawnSync('sh', ['-c', `command -v ${name}`], { encoding: 'utf8' })
  return (probe.status ?? 1) === 0
}

const args = parse(process.argv.slice(2))

if (!hasCommand('dsh')) {
  process.stderr.write('setup: dsh is not on PATH. Install official npm @deepseek-ai/dsh 0.1.1-rc.2+ first.\n')
  process.exit(1)
}

if (!args.skipNpm) {
  run(win ? 'npm.cmd' : 'npm', ['install', '--omit=dev'])
}

if (win) {
  run('powershell.exe', [
    '-NoProfile',
    '-ExecutionPolicy',
    'Bypass',
    '-File',
    join(root, 'scripts', 'link-dsh-deps.ps1'),
  ])
} else {
  run('sh', [join(root, 'scripts', 'link-dsh-deps.sh')])
}

const home = process.env.DSH_HOME || join(homedir(), '.dsh')
mkdirSync(home, { recursive: true })
const envPath = join(home, 'remote-host.env')
const lines = ['# generated by dsh-remote-host setup; safe to edit', `DSH_REMOTE_HOST_ROOT=${shellQuote(root)}`]
if (args.bind) lines.push(`DSH_REMOTE_BIND_ADDRESS=${shellQuote(args.bind)}`)
if (args.advertise) lines.push(`DSH_REMOTE_ADVERTISE_ADDRESS=${shellQuote(args.advertise)}`)
if (args.port) lines.push(`DSH_REMOTE_PORT=${shellQuote(args.port)}`)
if (args.webPort) lines.push(`DSH_WEB_PORT=${shellQuote(args.webPort)}`)
lines.push('')
writeFileSync(envPath, lines.join('\n'))

const childEnv = { ...process.env, DSH_HOME: process.env.DSH_HOME || home }
if (args.bind) childEnv.DSH_REMOTE_BIND_ADDRESS = args.bind
if (args.advertise) childEnv.DSH_REMOTE_ADVERTISE_ADDRESS = args.advertise
if (args.port) childEnv.DSH_REMOTE_PORT = args.port

const dump = spawnSync(
  win ? 'dsh.cmd' : 'dsh',
  ['--profile', 'web', '--patch', join(root, 'cordis.patch.yml'), '--dump-config'],
  { cwd: root, env: childEnv, encoding: 'utf8', shell: win, maxBuffer: 8 * 1024 * 1024 },
)
if ((dump.status ?? 1) !== 0) {
  process.stderr.write(dump.stderr || dump.stdout || 'setup: dump-config failed\n')
  process.exit(dump.status ?? 1)
}
const text = `${dump.stdout || ''}\n${dump.stderr || ''}`
const need = [
  '@w2112515/dsh-remote-host/admissions',
  '@w2112515/dsh-remote-host/control',
  '@w2112515/dsh-remote-host/command',
  '@w2112515/dsh-remote-host/remote',
  '@w2112515/dsh-remote-host/settings',
]
const missing = need.filter((name) => !text.includes(name))
if (missing.length > 0) {
  process.stderr.write(`setup: dump-config missing ${missing.join(', ')}\n`)
  process.exit(1)
}

const store = childEnv.DSH_REMOTE_SECURITY_STORE || join(home, 'remote-host-security.bin')
process.stdout.write(`setup ok\nenv file: ${envPath}\nidentity store: ${store}\n`)
process.stdout.write('Copy that store file to back up pairing. Losing it means every phone must pair again.\nnext:\n')
process.stdout.write(win ? '  .\\scripts\\start.ps1\n  node scripts/invite.mjs\n' : '  sh scripts/start.sh\n  node scripts/invite.mjs\n')
if (!args.bind) {
  process.stdout.write('No --bind set. For a public IPv4 Host, rerun with --bind YOUR_PUBLIC_IP or edit the env file.\n')
}
